---
title: "Mental well-being's effects on saving for an emergency fund"
font-family: 'Corbel'
author: Kieran Yuen
output: github_document
---
# Steps
1) Do 

# Hypotheses


Someone with great financial knowledge should have the understanding and foresight to save for the future/emergency fund.
*Make emergency fund the dependent variable and use the objective questions as independent variables.*

*In addition, maybe we can find correlations between our independent variables and some of the objective questions. These correlations might tell us something. For example, seeing if there is a correlation between someone who feels a lot of stress just thinking about finances but answered the objective questions correctly. I would expect to see that those with correct answers in the objective questions should have an emergency fund*

What type of people will have an emergency fund?

What kind of effect does mental well-being have in determining if someone has an emergency fund?

How does how you feel about your finances affect whether you have an emergency fund or not?


# Introduction
## Dataset used
The dataset I used is the National Financial Capability Study (NFCS) which was funded by the FINRA Investor Education and conducted by ARC Research. We will be focusing on one financial decision made by households, and that is the decision to save an emergency fund or not.

## Overall goal
To find possible reasons why someone might not have an emergency fund and propose ideas on how to address those issues to encourage/incentive people to have an emergency fund.

## Dependent variable
(J5) Emergency fund (Yes/No)
*Have you set aside emergency or rainy day funds that would cover your expenses for 3 months, in case of sickness, job loss, economic downturn, or other emergencies?*
Code this as 0/1, exclude don't know and prefer not to answer

## Independent variables (rate 1-10)
(J1) Personal Financial Condition
*Overall, thinking of your assets, debts and savings, how satisfied are you with your current personal financial condition?*
10 = Extremely Satisfied
1 = Not at all Satisfied

(J33_40) Anxiety about my personal finances (rate 1-7)
*How strongly do you agree or disagree with the following statements? - Thinking about my personal finances can make me feel anxious*
7 = Strongly agree
1 = Strongly disagree

(J33_41) Personal finances make me feel stressed (rate 1-7)
*How strongly do you agree or disagree with the following statements? - Discussing my finances can make my heart race or make me feel stressed*
7 = Strongly agree
1 = Strongly disagree


(G23) Too much debt right now in my life (rate 1-7)
*How strongly do you agree or disagree with the following statement? - I have too much debt right now*
7 = Strongly agree
1 = Strongly disagree


## Other variables to interact with ind. var.
### Interaction #1
Objective financial knowledge:anxiety/stressed about personal finances

Someone who objectively understands finances (but not necissarily confident) but is stressed or gets anixety from thinking about. 

How likely are they to have an emergency fund?

### Interaction #2
Subjective financial knowledge:anxiety/stressed about personal finances

Someone who is confident in their knowledge about personal finance (but not necissarily objectively knowledgeable about it) but is stressed/not stressed or gets anixety from thinking about. 

How likely are they to have an emergency fund?



 
# Questions to consider
Is "feeling confident" the same as "not feeling anxious" or "feeling great about my personal finance situation?"


# Literature Review

## Article #1
Jaclyn J. Beierlein, Margot Neverett, (2013). "Who takes personal finance?", http://ccny-proxy1.libr.ccny.cuny.edu/login?url=https://search.ebscohost.com/login.aspx?direct=true&db=bth&AN=94644713&site=ehost-live

This article has certainly peaked my interests because I always believed that if people took a course in personal finance that they would make much smarter decisions with their money.

### Data
Institutional data from admission applications and transcripts of 17,499 students at East Carolina University. I believe this type of data should be accessible by asking for it from a college or university if they can provide it to me anonymized.

### Econometric Techniques
They made dummy variables (0/1) of all the variables they have and ran a t-test to determine the difference between the group who took the personal finance course and those who did not. They also performed a logistic regression to account for spurious relationships amongst the variables. Used ordinal regression to analyze students' grades.

### What question is addressed?
This articles primary question is: What are the characteristics of traditional undergraduate students that take the university personal finance class?

### Findings
Assuming that enrollment in a personal finance course is considered showing as a measure of interest, women demonstrate less interest in personal finance than do men. Those with highest interest in a pesonal finance course are: men, business, human ecology an social science majors. Those students who are less likely to take a personal finance course are: women, students with higher verbal SAT scores and GPAs, and arts and education majors.


## Article #2
Hancock, Adam M.; Jorgensen, Bryce L.; Swanson, Melvin S., (2013). "College Students and Credit Card Use: The Role of Parents, Work Experience, Financial Knowledge, and Credit Card Attitudes", http://ccny-proxy1.libr.ccny.cuny.edu/login?url=https://search.ebscohost.com/login.aspx?direct=true&db=ecn&AN=1412539&site=ehost-live

### Data
The data they used were from the College Student Financial Literacy Surveys (CSFLS), which measures the financial knowledge, attitudes, behavior, influences, and personal demographics that may affect the fianncial literacy of college students.

### Econometric Techniques
Logistical regression to predict likelihood of having two or more credit cards. Logistical regression predicting likelihood of having more than $500 in credit card debt

### What question is addressed?
This study is trying to examine how students' credit card behaviors (i.e. number of credit cards and amount of debt) is influenced by: parental interactions, years of work experience, financial knowledge, credit card attitudes, and personal characteristics.

## Article #3
Henager, R., Cude, B.J. Financial Literacy of High School Graduates: Long- and Short-Term Financial Behavior by Age Group. J Fam Econ Iss 40, 564–575 (2019). https://doi.org/10.1007/s10834-019-09626-2

### Data
2015 National Financial Capability Study (NFCS) State-by-State Survey Instrument sponsored by the Financial Industry Regulation Authority (FINRA)

### Econometric Techniques
Ordered logistic regressions were run to analyze the key dependent variables (when the dependent variable was an index of behaviors; either 0-3 or 0-4). 

Logistic Regression was used for when the dependent variable was the short-term variable budgeting.

### What question is addressed?
Examine the influence of financial literacy and financial education on the long- and short-term financial behaviors, by age group for those without a college degree.

### Findings
The study found that confidence in both financial knowledge and financial ability are important influences on positive financial behaviors for those without a college degree.


## Article #4
Henager, Robin and Cude, Brenda J. Financial Literacy and Long- and Short-Term Financial Behavior in Different Age Groups. Journal of Financial Counseling and Planning Vol 27, 3-19 (2016). https://connect.springerpub.com/content/sgrjfcp/27/1/3

### Data
2012 National Financial Capability Study (NFCS) State-by-State Survey Instrument sponsored by the Financial Industry Regulation Authority (FINRA)

### Econometric Techniques
Ordered logistic regressions were run to analyze the key dependent variables (when the dependent variable was an index of behaviors; either 0-3 or 0-4). The Variance Inflation Factor (VIF) test was run to check for multicollinearity between the independent variables used in this study. The VIF test indicated no multicollinearity. Dependent variables were both long-term and short-term financial behaviors.

### What question is addressed?
Examine the influence of financial literacy and financial education on the long- and short-term financial behaviors, among various age groups (18-24, 25-34, 35-44, 45-54, 55-64, 65+).

### Findings
The study found that both objective and subjective financial literacy were positively associated with long- and short-term financial behaviors. 

In the younger age groups subjective financial knowledge had a stronger correlation than either objective financial knowledge or subjective financial management ability. This means that confidence in one's financial literacy mattered more when it came to making the right financial decisions than actual objective knowledge of the financial topic.

In the older age groups, objective financial knowledge was more strongly related to long-term financial behavior than either of the other two measures of financial literacy.This means the older age groups, objective financial knowledge translated to financial smarter decisions with their money than simply confidence in one's own self.

## Article #5
Birkenmaier J, Fu Q. The Association of Alternative Financial Services Usage and Financial Access: Evidence from the National Financial Capability Study. Journal of Family and Economic Issues. 2016;37(3):450-460. Accessed December 6, 2020. https://search-ebscohost-com.ccny-proxy1.libr.ccny.cuny.edu/login.aspx?direct=true&db=ecn&AN=1590468&site=ehost-live

### Data
2012 National Financial Capability Study (NFCS) State-by-State Survey Instrument sponsored by the Financial Industry Regulation Authority (FINRA)

### Econometric Techniques
OLS

### What question is addressed?
Association of financial access and alternative financial services

### Findings
Results suggested that being unbanked was positively associated with AFS usage after controlling for other covariates

## Article #6
Nicolini G, Cude BJ. The Influence of Financial Well-Being on Pawnshop Use. Journal of Consumer Affairs. 2019;53(4):1674-1692. Accessed December 6, 2020. https://search-ebscohost-com.ccny-proxy1.libr.ccny.cuny.edu/login.aspx?direct=true&db=ecn&AN=1845572&site=ehost-live

### Data
2015 National Financial Capability Study (NFCS) State-by-State Survey Instrument sponsored by the Financial Industry Regulation Authority (FINRA)

### Econometric Techniques


### What question is addressed?
The influence of financial well-being on pawnshop use. Financial well-being, based on the Consumer Financial Protection Bureau's definition

### Findings
A higher financial well-being reduced the odds of pawnshop use by 17%, even after controlling for having a bank account, having a credit card, being financially overconfident, proximity to local pawnshops, and selected demographic characteristics


## Article #7
Despard MR, Friedline T, Martin-West S. Why Do Households Lack Emergency Savings? The Role of Financial Capability. Journal of Family and Economic Issues. 2020;41(3):542-557. Accessed December 6, 2020. https://search-ebscohost-com.ccny-proxy1.libr.ccny.cuny.edu/login.aspx?direct=true&db=ecn&AN=1848145&site=ehost-live

### Data
2009, 2012, 2015, and 2018  National Financial Capability Study (NFCS) State-by-State Survey Instrument sponsored by the Financial Industry Regulation Authority (FINRA)

### Econometric Techniques


### What question is addressed?
Why Do Households Lack Emergency Savings? The Role of Financial Capability

### Findings
Subjective financial knowledge, financial confidence, and savings account ownership, but not objective financial knowledge, were significant and consistent predictors of having an emergency fund. Savings account ownership was the strongest predictor, accounting for an increase in the probability of having an emergency fund of 25% to 29% across study years. Adding homeownership and ability to cover expenses to the models increased the proportion of variance explained by an average of 29%. 


## Article #8
Babiarz P, Robb CA. Financial Literacy and Emergency Saving. Journal of Family and Economic Issues. 2014;35(1):40-50. Accessed December 6, 2020. https://search-ebscohost-com.ccny-proxy1.libr.ccny.cuny.edu/login.aspx?direct=true&db=ecn&AN=1430913&site=ehost-live

### Data
2009, 2012, 2015, and 2018  National Financial Capability Study (NFCS) State-by-State Survey Instrument sponsored by the Financial Industry Regulation Authority (FINRA)

### Econometric Techniques


### What question is addressed?
Why Do Households Lack Emergency Savings? The Role of Financial Capability

### Findings
Subjective financial knowledge, financial confidence, and savings account ownership, but not objective financial knowledge, were significant and consistent predictors of having an emergency fund. Savings account ownership was the strongest predictor, accounting for an increase in the probability of having an emergency fund of 25% to 29% across study years. Adding homeownership and ability to cover expenses to the models increased the proportion of variance explained by an average of 29%. 



# Means (simple graphs, correlations, differences of means)


# Simple Regressions
Do logistic regression on 

# Complicated Regressions


# Conclusion (Explain Results)

*Add a statment about how this fits into the larger picture of financial literacy*
*How this study can continue to be studied/what I can further study*
*Understand that we cannot know everything, there are limitations to what we can know and what we can even find out*

# Limitations
We do not know where people are holding their 3 months of emergency funds. Whether that is in their savings account or invested in the stock market. 



# Questions for Professor Foster
What is confirmatory factor analysis? is this the same where Lasso tells us which variables are most important? Per Kevin, it is the same as the variable importance selection tools we have used as in class.



Per Kevin, when I run the objective and subjective financial knowledge questions I should be able to see the same results as what I saw in previous studies.

Logit can give misleading results when we have "factors."

Per Kevin, Income would be endogenous to what we would spend it on

The reason macro data is problematic is because the data is wider than it is longer. That is because macro data is collected on a quarterly level so even if we go back all the way to 1955. there would not be enough data. 

What should I do with the "weights" in my data?


```{r Loading NFCS database}
library(haven)
NFCS_2018_State_Data <- read_sav("NFCS 2018 State Data.sav")
View(NFCS_2018_State_Data)
```









